const CHARACTER_DETAIL = {
  FETCH_CHARACTER_DETAIL_PENDING: "FETCH_CHARACTER_DETAIL_PENDING",
  FETCH_CHARACTER_DETAIL_SUCCESS: "FETCH_CHARACTER_DETAIL_SUCCESS",
  FETCH_CHARACTER_DETAIL_FAILURE: "FETCH_CHARACTER_DETAIL_FAILURE"
};

export default CHARACTER_DETAIL;
